blank_issues_enabled: false
contact_links:
  - name: Bug Report
    url: https://github.com/fam007e/libexecinfo/issues/new?template=bug_report.md
    about: File a bug report for the project.
  - name: Feature Request
    url: https://github.com/fam007e/libexecinfo/issues/new?template=feature_request.md
    about: Suggest a new feature for the project.
